name: Build and push Docker image

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CPU_ARCH:
          - aarch64
          - i686
          - x86_64
    steps:

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Setup binfmt_misc
      if: (matrix.CPU_ARCH == 'aarch64') || (matrix.CPU_ARCH == 'arm')
      run: docker run --rm --privileged aptman/qus -s -- -p aarch64 arm

    - name: Build images
      run: |
        case '${{ matrix.CPU_ARCH }}' in
          arm|aarch64) SYSTEM_TYPE=arm;;
          *) SYSTEM_TYPE=x86;;
        esac
        docker build -t \
          docker.io/xeffyr/termux:${{ matrix.CPU_ARCH }} \
          -f ./Dockerfile \
          --build-arg BOOTSTRAP_ARCH=${{ matrix.CPU_ARCH }} \
          --build-arg SYSTEM_TYPE="${SYSTEM_TYPE}" \
          .

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'termux/termux-docker'
      uses: docker/login-action@v1
      with:
        username: xeffyr
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'termux/termux-docker'
      run: |
        docker push docker.io/xeffyr/termux:${{ matrix.CPU_ARCH }}
        if [ ${{ matrix.CPU_ARCH }} = i686 ]; then
          docker tag docker.io/xeffyr/termux:i686 docker.io/xeffyr/termux:latest
          docker push docker.io/xeffyr/termux:latest
        fi


  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup QEMU
      run: docker run --rm --privileged aptman/qus -s -- -p aarch64

    - run: docker pull xeffyr/termux:aarch64

    - name: Test build scripts
      run: |
        docker run \
          -u 0 \
          -v $(pwd):/data/data/com.termux/files/home/packages \
          -w /data/data/com.termux/files/home/packages \
          --entrypoint sh \
          xeffyr/termux:aarch64 \
          -c ./test.sh
